albumCollection = [
  [ { idArtist: '111480',
      albumName: 'Lateralus', 
      yearReleased: 2001, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { 
      idArtist: '111480', 
      albumName: 'Undertow', 
      yearReleased: 1993, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' }, 
    { 
      idArtist: '111480', 
      albumName: '10,000 Days', 
      yearReleased: 2006, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { idArtist: '111480', 
      albumName: 'Ænima', 
      yearReleased: 1996, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { 
      idArtist: '111480', 
      albumName: 'Opiate', 
      yearReleased: 1992, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { 
      idArtist: '111480', 
      albumName: 'Salival', 
      yearReleased: 2000, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { idArtist: '111480', 
      albumName: '72826', 
      yearReleased: 1991, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { idArtist: '111480', 
      albumName: 'Fear Inoculum', 
      yearReleased: 2019, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal'
    } 
],
  { idArtist: '112009',
    albumName: Null
  },
  [ { idArtist: '111308',
    albumName: 'Musicology',
    yearReleased: 2004,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Gold Experience',
    yearReleased: 1995,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Camille',
    yearReleased: 1986,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'One Man Jam',
    yearReleased: 2002,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Studio Nights: The Rebels',
    yearReleased: 1979,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Rainbow Children',
    yearReleased: 2001,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Vault... Old Friends 4 Sale',
    yearReleased: 1999,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Dirty Mind',
    yearReleased: 1980,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Undertaker',
    yearReleased: 1993,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Prince',
    yearReleased: 1979,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: '1999',
    yearReleased: 1982,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Chaos and Disorder',
    yearReleased: 1996,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'For You',
    yearReleased: 1978,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Rave Un2 the Joy Fantastic',
    yearReleased: 1999,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Chocolate Invasion',
    yearReleased: 2004,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Controversy',
    yearReleased: 1981,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Lovesexy',
    yearReleased: 1988,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Black Album',
    yearReleased: 1994,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Xpectation',
    yearReleased: 2003,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Crystal Ball',
    yearReleased: 1998,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Come',
    yearReleased: 1994,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Purple Rain',
    yearReleased: 1984,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Sign “☮” the Times',
    yearReleased: 1987,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Batman',
    yearReleased: 1989,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Scandalous Sex Suite (feat. Kim Basinger)',
    yearReleased: 1989,
    albumArtist: 'Prince',
    albumGenre: 'Funk' } 
  ],
  [ { idArtist: '111615',
    albumName: 'Fly by Night',
    yearReleased: 1975,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Moving Pictures',
    yearReleased: 1981,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Vapor Trails',
    yearReleased: 2002,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Clockwork Angels',
    yearReleased: 2012,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Hemispheres',
    yearReleased: 1978,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'A Farewell to Kings',
    yearReleased: 1977,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Signals',
    yearReleased: 1982,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Permanent Waves',
    yearReleased: 1980,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Counterparts',
    yearReleased: 1993,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: '2112',
    yearReleased: 1976,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Test for Echo',
    yearReleased: 1996,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Snakes & Arrows',
    yearReleased: 2007,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Caress of Steel',
    yearReleased: 1975,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Hold Your Fire',
    yearReleased: 1987,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Presto',
    yearReleased: 1989,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Roll the Bones',
    yearReleased: 1991,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Power Windows',
    yearReleased: 1985,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Grace Under Pressure',
    yearReleased: 1984,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Rush: Time Machine 2011 - Live in Cleveland',
    yearReleased: 2011,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'All the World\'s a Stage',
    yearReleased: 1976,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Exit... Stage Left',
    yearReleased: 1981,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'A Show of Hands',
    yearReleased: 1989,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Rush',
    yearReleased: 1974,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Different Stages Live',
    yearReleased: 1998,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Rush in Rio',
    yearReleased: 2003,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' } 
  ],
  [ { idArtist: '112192',
    albumName: 'Morning View',
    yearReleased: 2001,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Make Yourself',
    yearReleased: 1999,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Light Grenades',
    yearReleased: 2006,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'If Not Now, When?',
    yearReleased: 2011,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'S.C.I.E.N.C.E.',
    yearReleased: 1997,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'A Crow Left of the Murder...',
    yearReleased: 2004,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Monuments and Melodies',
    yearReleased: 2009,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'The Essential',
    yearReleased: 2012,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Fungus Amongus',
    yearReleased: 1995,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Live at Lollapalooza 2003',
    yearReleased: 2003,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Enjoy Incubus',
    yearReleased: 1997,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Trust Fall (Side A)',
    yearReleased: 2015,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: '8',
    yearReleased: 2017,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Playlist: The Very Best of Incubus',
    yearReleased: 2015,
    albumArtist: 'Incubus',
    albumGenre: '' } 
  ],
]