albumCollection = [
  [ { idArtist: '111480',
      albumName: 'Lateralus', 
      yearReleased: 2001, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { 
      idArtist: '111480', 
      albumName: 'Undertow', 
      yearReleased: 1993, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' }, 
    { 
      idArtist: '111480', 
      albumName: '10,000 Days', 
      yearReleased: 2006, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { idArtist: '111480', 
      albumName: 'Ænima', 
      yearReleased: 1996, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { 
      idArtist: '111480', 
      albumName: 'Opiate', 
      yearReleased: 1992, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { 
      idArtist: '111480', 
      albumName: 'Salival', 
      yearReleased: 2000, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { idArtist: '111480', 
      albumName: '72826', 
      yearReleased: 1991, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { idArtist: '111480', 
      albumName: 'Fear Inoculum', 
      yearReleased: 2019, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal'
    } 
  ],
  [ { idArtist: '112009',
    albumName: 'Steal This Album!',
    yearReleased: 2002,
    albumArtist: 'System of a Down',
    albumGenre: 'Alternative Metal' },
  { idArtist: '112009',
    albumName: 'Hypnotize',
    yearReleased: 2005,
    albumArtist: 'System of a Down',
    albumGenre: 'Alternative Metal' },
  { idArtist: '112009',
    albumName: 'Mezmerize',
    yearReleased: 2005,
    albumArtist: 'System of a Down',
    albumGenre: 'Alternative Metal' },
  { idArtist: '112009',
    albumName: 'Toxicity',
    yearReleased: 0,
    albumArtist: 'System of a Down',
    albumGenre: '' },
  { idArtist: '112009',
    albumName: 'System of a Down',
    yearReleased: 1998,
    albumArtist: 'System of a Down',
    albumGenre: 'Alternative Metal' },
  { idArtist: '112009',
    albumName: 'Toxicity II',
    yearReleased: 2001,
    albumArtist: 'System of a Down',
    albumGenre: 'Alternative Metal' } 
  ],
   { idArtist: '111308',
    albumName: 'Musicology',
    yearReleased: 2004,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Gold Experience',
    yearReleased: 1995,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Camille',
    yearReleased: 1986,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'One Man Jam',
    yearReleased: 2002,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Studio Nights: The Rebels',
    yearReleased: 1979,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Rainbow Children',
    yearReleased: 2001,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Vault... Old Friends 4 Sale',
    yearReleased: 1999,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Dirty Mind',
    yearReleased: 1980,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Undertaker',
    yearReleased: 1993,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Prince',
    yearReleased: 1979,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: '1999',
    yearReleased: 1982,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Chaos and Disorder',
    yearReleased: 1996,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'For You',
    yearReleased: 1978,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Rave Un2 the Joy Fantastic',
    yearReleased: 1999,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Chocolate Invasion',
    yearReleased: 2004,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Controversy',
    yearReleased: 1981,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Lovesexy',
    yearReleased: 1988,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Black Album',
    yearReleased: 1994,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Xpectation',
    yearReleased: 2003,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Crystal Ball',
    yearReleased: 1998,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Come',
    yearReleased: 1994,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Purple Rain',
    yearReleased: 1984,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Sign “☮” the Times',
    yearReleased: 1987,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Batman',
    yearReleased: 1989,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Scandalous Sex Suite (feat. Kim Basinger)',
    yearReleased: 1989,
    albumArtist: 'Prince',
    albumGenre: 'Funk' } 
  ],
  [ { idArtist: '111615',
    albumName: 'Fly by Night',
    yearReleased: 1975,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Moving Pictures',
    yearReleased: 1981,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Vapor Trails',
    yearReleased: 2002,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Clockwork Angels',
    yearReleased: 2012,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Hemispheres',
    yearReleased: 1978,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'A Farewell to Kings',
    yearReleased: 1977,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Signals',
    yearReleased: 1982,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Permanent Waves',
    yearReleased: 1980,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Counterparts',
    yearReleased: 1993,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: '2112',
    yearReleased: 1976,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Test for Echo',
    yearReleased: 1996,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Snakes & Arrows',
    yearReleased: 2007,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Caress of Steel',
    yearReleased: 1975,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Hold Your Fire',
    yearReleased: 1987,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Presto',
    yearReleased: 1989,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Roll the Bones',
    yearReleased: 1991,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Power Windows',
    yearReleased: 1985,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Grace Under Pressure',
    yearReleased: 1984,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Rush: Time Machine 2011 - Live in Cleveland',
    yearReleased: 2011,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'All the World\'s a Stage',
    yearReleased: 1976,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Exit... Stage Left',
    yearReleased: 1981,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'A Show of Hands',
    yearReleased: 1989,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Rush',
    yearReleased: 1974,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Different Stages Live',
    yearReleased: 1998,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Rush in Rio',
    yearReleased: 2003,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' } 
  ],
  [ { idArtist: '112192',
    albumName: 'Morning View',
    yearReleased: 2001,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Make Yourself',
    yearReleased: 1999,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Light Grenades',
    yearReleased: 2006,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'If Not Now, When?',
    yearReleased: 2011,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'S.C.I.E.N.C.E.',
    yearReleased: 1997,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'A Crow Left of the Murder...',
    yearReleased: 2004,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Monuments and Melodies',
    yearReleased: 2009,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'The Essential',
    yearReleased: 2012,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Fungus Amongus',
    yearReleased: 1995,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Live at Lollapalooza 2003',
    yearReleased: 2003,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Enjoy Incubus',
    yearReleased: 1997,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Trust Fall (Side A)',
    yearReleased: 2015,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: '8',
    yearReleased: 2017,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Playlist: The Very Best of Incubus',
    yearReleased: 2015,
    albumArtist: 'Incubus',
    albumGenre: '' } 
  ],
  [ { idArtist: '132746',
    albumName: 'Hozier',
    yearReleased: 2014,
    albumArtist: 'Hozier',
    albumGenre: 'Indie Rock' },
  { idArtist: '132746',
    albumName: 'Wasteland, Baby!',
    yearReleased: 2019,
    albumArtist: 'Hozier',
    albumGenre: 'Pop' } 
  ],
  [ { idArtist: '112378',
    artistName: 'Mika',
    albumGenre: 'Pop',
    website: 'www.mikasounds.com',
    biography: 'Mika ( born Michael Holbrook Penniman, Jr.; 18 August 1983) is a British singer-songwriter.\nAfter recording his first extended play, Dodgy Holiday EP, Mika released his first full-length studio album, Life in Cartoon Motion, on Island Records in 2007. Life in Cartoon Motion sold more than 5.6 million copies worldwide and helped Mika win a Brit Award-winning Best British Breakthrough act, and receive a Grammy Award nomination. In 2006, Mika started up his company, Dodgy Holiday Tours Limited. Two years later Mika released his second extended play, Songs for Sorrow, of which limited edition copies are now sold out worldwide. In 2009 Mika released his second studio album, The Boy Who Knew Too Much. Finishing his worldwide tour, Mika started writing and recording material for his third album, The Origin of Love, stating it will be "more simplistic pop, less layered than the last one". The album will be released on 16 September 2012.\nMika was born in Beirut, the third of five children born to a Syrian mother and an American father. When he was a year old his family was forced to leave war-torn Lebanon and moved to Paris. The first piano piece he learned to play was "Les Champs-Élysées", by Joe Dassin. At age seven, he wrote his first song, which he describes as an "awful" piano instrumental called "Angry". The family moved to London when he was nine years old. There, he attended the Lycée Français Charles de Gaulle, where he experienced severe bullying. He also had problems with dyslexia. In response to these experiences Mika was home-schooled by his mother at the age of 12, for six to eight months. He then attended St Philip\'s School in Kensington, where he was the head of the Schola Cantorum (the St. Philip\'s Choir). Later he attended Westminster School and the Royal College of Music, which he left to record his first album at Casablanca Records. He has also slightly altered his given name, Mica, changing the "c" to a "k" because he was frustrated by how often people would mispronounce it.\n\nMika has one younger brother and one younger sister along with two older sisters. His sister Yasmine, who works as an artist under the nom de plume DaWack, painted the cartoon art for his two albums Life in Cartoon Motion and The Boy Who Knew Too Much, and she is currently a fashion designer. Mika speaks French and Spanish fluently; in an interview on 28 September 2009 with The Chris Moyles Show on BBC Radio 1 he commented that he had taken Mandarin Chinese for 9 years but did not speak it very well; he also mentioned that his three sisters did all speak it fluently. He also speaks a little bit of Arabic with a Lebanese dialect, his mother\'s native tongue.\n\nAs a child Mika was trained by Alla Ardakov (Ablaberdyeva), a Russian opera professional, and later attended the Royal College of Music in London. His debut radio appearance was on Dermot O\'Leary\'s BBC Radio 2 show in September 2006. He also appeared on Later... with Jools Holland, and on The Friday Night Project on 19 January 2007. Mika is rumoured to have a vocal range of five octaves, but claims that it is actually closer to three and a half octaves.\n\nMika denied allegations that he is steering clear of sexual taboos in order to appeal to the US market, pointing to the song "Billy Brown", which is about a married man who has an affair with another man. He is quoted as saying, "If I was worried about sexual taboos I certainly wouldn\'t have made the record I made. It has nothing to do with that. It has more to do with self-respect." In an interview in the US gay magazine Out he stated that "there is a way of discussing sexuality without using labels."\n\nIn a September 2009 interview in Gay & Night Mika commented on his sexuality: "I\'ve never ever labelled myself. But having said that; I\'ve never limited my life, I\'ve never limited who I sleep with... Call me whatever you want. Call me bisexual, if you need a term for me..." Later he stated in an interview with This Is London "I consider myself label-less because I could fall in love with anybody - literally - any type, any body. I\'m not picky." In an August 2012 interview with the magazine Instinct, the singer described himself as gay.\n\nIn March 2010, Mika was named in France a Knight of the Order of Arts and Letters for services to music.' } 
  ],
  [ { idArtist: '112378',
    albumName: 'Life in Cartoon Motion',
    yearReleased: 2007,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'The Boy Who Knew Too Much',
    yearReleased: 2009,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'The Origin of Love',
    yearReleased: 2012,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'Songbook, Volume 1',
    yearReleased: 2013,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'Boum Boum Boum',
    yearReleased: 2014,
    albumArtist: 'Mika',
    albumGenre: '' },
  { idArtist: '112378',
    albumName: 'No Place In Heaven',
    yearReleased: 2015,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'Popular Song',
    yearReleased: 2012,
    albumArtist: 'MIKA',
    albumGenre: '' },
  { idArtist: '112378',
    albumName: 'My Name Is Michael Holbrook',
    yearReleased: 2019,
    albumArtist: 'MIKA',
    albumGenre: null } 
  ],
  [ { idArtist: '138966',
    albumName: 'Room 93',
    yearReleased: 2014,
    albumArtist: 'Halsey',
    albumGenre: 'Indie Pop' },
  { idArtist: '138966',
    albumName: 'Badlands',
    yearReleased: 2015,
    albumArtist: 'Halsey',
    albumGenre: 'Indie Pop' },
  { idArtist: '138966',
    albumName: 'hopeless fountain kingdom',
    yearReleased: 2017,
    albumArtist: 'Halsey',
    albumGenre: 'Indie Pop' },
  { idArtist: '138966',
    albumName: 'Now or Never',
    yearReleased: 2017,
    albumArtist: 'Halsey',
    albumGenre: '' },
  { idArtist: '138966',
    albumName: 'Strangers',
    yearReleased: 2017,
    albumArtist: 'Halsey',
    albumGenre: '' },
  { idArtist: '138966',
    albumName: 'Without Me',
    yearReleased: 2018,
    albumArtist: 'Halsey',
    albumGenre: 'Indie Pop' },
  { idArtist: '138966',
    albumName: 'Nightmare',
    yearReleased: 2019,
    albumArtist: 'Halsey',
    albumGenre: null },
  { idArtist: '138966',
    albumName: 'Graveyard',
    yearReleased: 2019,
    albumArtist: 'Halsey',
    albumGenre: null },
  { idArtist: '138966',
    albumName: 'clementine',
    yearReleased: 2019,
    albumArtist: 'Halsey',
    albumGenre: null } 
  ],
  [ { idArtist: '113256',
    albumName: 'The Strange Case of...',
    yearReleased: 2012,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'Halestorm',
    yearReleased: 2009,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: '(Don\'t Mess With the) Time Man',
    yearReleased: 1999,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'ReAniMate: The CoVeRs eP',
    yearReleased: 2011,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'ReAniMate 2.0: The CoVeRs eP',
    yearReleased: 2013,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'In the Live Room',
    yearReleased: 2012,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'Into the Wild Life',
    yearReleased: 2015,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'One and Done',
    yearReleased: 2005,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'Live in Philly 2010',
    yearReleased: 2010,
    albumArtist: 'Halestorm',
    albumGenre: 'Hard Rock' },
  { idArtist: '113256',
    albumName: 'ReAniMate 3.0: The CoVeRs eP',
    yearReleased: 2017,
    albumArtist: 'Halestorm',
    albumGenre: 'Hard Rock' },
  { idArtist: '113256',
    albumName: 'Vicious',
    yearReleased: 2018,
    albumArtist: 'Halestorm',
    albumGenre: 'Hard Rock' } 
  ],
  [ { idArtist: '111939',
    albumName: 'Imaginaerum',
    yearReleased: 2011,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Angels Fall First',
    yearReleased: 1997,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Oceanborn',
    yearReleased: 1998,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Once',
    yearReleased: 2004,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Dark Passion Play',
    yearReleased: 2007,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Wishmaster',
    yearReleased: 2000,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Century Child',
    yearReleased: 2002,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'From Wishes to Eternity: Live',
    yearReleased: 2001,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'End of Innocence',
    yearReleased: 2003,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'End of an Era',
    yearReleased: 2006,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Made in Hong Kong (and in Various Other Places)',
    yearReleased: 2009,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Over the Hills and Far Away',
    yearReleased: 2001,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Wishmastour 2000',
    yearReleased: 2001,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Highest Hopes: The Best of Nightwish',
    yearReleased: 2005,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Imaginaerum (The Score)',
    yearReleased: 2012,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Showtime, Storytime',
    yearReleased: 2013,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Endless Forms Most Beautiful',
    yearReleased: 2015,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Greatest Hits',
    yearReleased: 2008,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Tales From the Elvenpath',
    yearReleased: 2004,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Decades',
    yearReleased: 2018,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' }
  ],
  [ { idArtist: '114364',
    albumName: '4',
    yearReleased: 2011,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'I Am... Sasha Fierce',
    yearReleased: 2008,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'B\'Day',
    yearReleased: 2006,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'Dangerously in Love',
    yearReleased: 2003,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: '4 Intimate Nights With Beyoncé',
    yearReleased: 2011,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'Beyoncé',
    yearReleased: 2013,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'Check on It',
    yearReleased: 2005,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'I Am... Yours: An Intimate Performance at Wynn Las Vegas',
    yearReleased: 2009,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: '1+1',
    yearReleased: 2011,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'I Am... World Tour',
    yearReleased: 2010,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'Dance For You',
    yearReleased: 2011,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: '7/11',
    yearReleased: 2014,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'The Soundtracks Collection',
    yearReleased: 2011,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'Formation',
    yearReleased: 2016,
    albumArtist: 'Beyoncé',
    albumGenre: 'R&B' },
  { idArtist: '114364',
    albumName: 'The Singles Collection',
    yearReleased: 2009,
    albumArtist: 'Beyoncé',
    albumGenre: '' },
  { idArtist: '114364',
    albumName: 'Lemonade',
    yearReleased: 2016,
    albumArtist: 'Beyoncé',
    albumGenre: 'Pop' },
  { idArtist: '114364',
    albumName: 'Single Ladies (Put a Ring on It) Dance Mixes',
    yearReleased: 2009,
    albumArtist: 'Beyoncé',
    albumGenre: '' },
  { idArtist: '114364',
    albumName: 'Greatest Hits',
    yearReleased: 2009,
    albumArtist: 'Beyoncé',
    albumGenre: '' },
  { idArtist: '114364',
    albumName: '4: The Remix',
    yearReleased: 2012,
    albumArtist: 'Beyoncé',
    albumGenre: 'R&B' },
  { idArtist: '114364',
    albumName: 'Revolution',
    yearReleased: 2009,
    albumArtist: 'Beyoncé',
    albumGenre: 'R&B' },
  { idArtist: '114364',
    albumName: 'Above and Beyoncé: Dance Mixes',
    yearReleased: 2009,
    albumArtist: 'Beyoncé',
    albumGenre: 'R&B' },
  { idArtist: '114364',
    albumName: 'Why Don\'t You Love Me',
    yearReleased: 2010,
    albumArtist: 'Beyoncé',
    albumGenre: '' },
  { idArtist: '114364',
    albumName: '711',
    yearReleased: 2014,
    albumArtist: 'Beyoncé',
    albumGenre: '' },
  { idArtist: '114364',
    albumName: '1+1',
    yearReleased: 2011,
    albumArtist: 'Beyoncé',
    albumGenre: '' },
  { idArtist: '114364',
    albumName: 'From The Beginning - The Best',
    yearReleased: 2010,
    albumArtist: 'Beyoncé',
    albumGenre: '' } 
  ],
  [ { idArtist: '111329',
    albumName: 'Sale el sol',
    yearReleased: 2010,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Laundry Service',
    yearReleased: 2001,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Dónde están los ladrones?',
    yearReleased: 1998,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'She Wolf',
    yearReleased: 2009,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Servicio de lavandería',
    yearReleased: 2001,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Pies descalzos',
    yearReleased: 1996,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Loba',
    yearReleased: 2009,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Magia',
    yearReleased: 1991,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Fijación Oral, Volume 1',
    yearReleased: 2005,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Peligro',
    yearReleased: 1993,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Grandes éxitos',
    yearReleased: 2002,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Live & Off the Record',
    yearReleased: 2004,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'MTV Unplugged',
    yearReleased: 2000,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Oral Fixation Tour / Tour Fijación Oral',
    yearReleased: 2007,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Shakira.',
    yearReleased: 2014,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Love in the Time of Cholera EP',
    yearReleased: 2007,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Dare (La La La)',
    yearReleased: 2014,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Oral Fixation, Volume 2',
    yearReleased: 2005,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Hips Don\'t Lie',
    yearReleased: 2006,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'La tortura',
    yearReleased: 2005,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Live From Paris',
    yearReleased: 2011,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Try Everything',
    yearReleased: 2016,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Waka Waka',
    yearReleased: 2010,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'Chantaje',
    yearReleased: 2016,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' },
  { idArtist: '111329',
    albumName: 'El Dorado',
    yearReleased: 2017,
    albumArtist: 'Shakira',
    albumGenre: 'Latin' } 
  ],
  [ { idArtist: '111279',
    albumName: 'Lulu',
    yearReleased: 2011,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Master of Puppets',
    yearReleased: 1986,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Death Magnetic',
    yearReleased: 2008,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: '…and Justice for All',
    yearReleased: 1988,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'St. Anger',
    yearReleased: 2003,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Load',
    yearReleased: 1996,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Garage Inc.',
    yearReleased: 1998,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Metallica',
    yearReleased: 1991,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Kill \'em All',
    yearReleased: 1983,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Reload',
    yearReleased: 1997,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'S&M',
    yearReleased: 1999,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Live Shit: Binge & Purge',
    yearReleased: 1993,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Orgullo, pasión, y gloria: Tres noches en La Ciudad de México',
    yearReleased: 2009,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'The $5.98 E.P.: Garage Days Re-Revisited',
    yearReleased: 1987,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Some Kind of Monster',
    yearReleased: 2003,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Six Feet Down Under EP',
    yearReleased: 2010,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Six Feet Down Under EP, Part II',
    yearReleased: 2010,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'The Videos: 1989–2004',
    yearReleased: 2006,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: '2007-06-28: Super Rock Super Bock Festival, Lisbon, Portugal',
    yearReleased: 2007,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: '2008-08-09: Ozzfest, Dallas, TX, USA',
    yearReleased: 2008,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'The Unnamed Feeling E.P.',
    yearReleased: 2004,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Very Best \'98',
    yearReleased: 1998,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Lords of Summer',
    yearReleased: 2014,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'I Disappear',
    yearReleased: 2000,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' },
  { idArtist: '111279',
    albumName: 'Nothing Else Matters',
    yearReleased: 1992,
    albumArtist: 'Metallica',
    albumGenre: 'Thrash Metal' } 
  ],
  [ { idArtist: '111238',
    albumName: 'Sheer Heart Attack',
    yearReleased: 1974,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'The Miracle',
    yearReleased: 1989,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Hot Space',
    yearReleased: 1982,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'The Works',
    yearReleased: 1984,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'The Game',
    yearReleased: 1980,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Made in Heaven',
    yearReleased: 1995,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Queen',
    yearReleased: 1973,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'A Kind of Magic',
    yearReleased: 1986,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Queen II',
    yearReleased: 1974,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'A Day at the Races',
    yearReleased: 1976,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'News of the World',
    yearReleased: 1977,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Innuendo',
    yearReleased: 1991,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Greatest Hits I & II',
    yearReleased: 1994,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'A Night at the Opera',
    yearReleased: 1975,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Live at Wembley \'86',
    yearReleased: 1992,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Flash Gordon',
    yearReleased: 1980,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Queen on Fire: Live at the Bowl',
    yearReleased: 2004,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Rock Montreal',
    yearReleased: 2007,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Queen\'s First E.P.',
    yearReleased: 1977,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Jazz',
    yearReleased: 1978,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Live Killers',
    yearReleased: 1979,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Greatest Hits',
    yearReleased: 1981,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Greatest Hits II',
    yearReleased: 1991,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Greatest Hits III',
    yearReleased: 1999,
    albumArtist: 'Queen',
    albumGenre: 'Rock' },
  { idArtist: '111238',
    albumName: 'Live Magic',
    yearReleased: 1986,
    albumArtist: 'Queen',
    albumGenre: 'Rock' } 
  ],
  [ { idArtist: '113811',
    albumName: 'Hollyweird',
    yearReleased: 2002,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'Poison\'d!',
    yearReleased: 2007,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'Crack a Smile... and More!',
    yearReleased: 2000,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'Look What the Cat Dragged In',
    yearReleased: 1986,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'Open Up and Say... Ahh!',
    yearReleased: 1988,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'Native Tongue',
    yearReleased: 1993,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'Flesh & Blood',
    yearReleased: 1990,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'Poison\'s Greatest Hits 1986-1996',
    yearReleased: 1996,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'Best of Ballads and Blues',
    yearReleased: 2003,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'Swallow This Live',
    yearReleased: 1991,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' },
  { idArtist: '113811',
    albumName: 'The Best of Poison: 20 Years of Rock',
    yearReleased: 2006,
    albumArtist: 'Poison',
    albumGenre: 'Hard Rock' } 
  ],
  [ { idArtist: '111564',
    albumName: 'Absolution',
    yearReleased: 2003,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'The Resistance',
    yearReleased: 2009,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Showbiz',
    yearReleased: 1999,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Black Holes and Revelations',
    yearReleased: 2006,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Origin of Symmetry',
    yearReleased: 2001,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Hullabaloo Soundtrack',
    yearReleased: 2002,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'HAARP',
    yearReleased: 2008,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Absolution Tour',
    yearReleased: 2005,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'The 2nd Law',
    yearReleased: 2012,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'OuiFm Accoustic Session',
    yearReleased: 1999,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Live at Rome Olympic Stadium',
    yearReleased: 2013,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Neutron Star Collision (Love Is Forever)',
    yearReleased: 2010,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Drones',
    yearReleased: 2015,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Hullabaloo: Live at Le Zenith, Paris',
    yearReleased: 2002,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Muscle Museum',
    yearReleased: 1999,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Muse EP',
    yearReleased: 1998,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Dig Down',
    yearReleased: 2017,
    albumArtist: 'Muse',
    albumGenre: '' },
  { idArtist: '111564',
    albumName: 'Futurism',
    yearReleased: 2010,
    albumArtist: 'Muse',
    albumGenre: '' },
  { idArtist: '111564',
    albumName: 'Essentials',
    yearReleased: 2018,
    albumArtist: 'Muse',
    albumGenre: '' },
  { idArtist: '111564',
    albumName: 'Simulation Theory',
    yearReleased: 2018,
    albumArtist: 'Muse',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111564',
    albumName: 'Greatest Hits',
    yearReleased: 2012,
    albumArtist: 'Muse',
    albumGenre: null } 
  ],
  [ { idArtist: '119231',
    albumName: 'Dirty Deeds Done Dirt Cheap',
    yearReleased: 1976,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Highway to Hell',
    yearReleased: 1979,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Stiff Upper Lip',
    yearReleased: 2000,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Let There Be Rock',
    yearReleased: 1977,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Powerage',
    yearReleased: 1978,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Back in Black',
    yearReleased: 1980,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'T.N.T.',
    yearReleased: 1975,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Black Ice',
    yearReleased: 2008,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'High Voltage',
    yearReleased: 1976,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Blow Up Your Video',
    yearReleased: 1988,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Fly on the Wall',
    yearReleased: 1985,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'The Razors Edge',
    yearReleased: 1990,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'For Those About to Rock (We Salute You)',
    yearReleased: 1981,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Ballbreaker',
    yearReleased: 1995,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Flick of the Switch',
    yearReleased: 1983,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Who Made Who',
    yearReleased: 1986,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'If You Want Blood You\'ve Got It',
    yearReleased: 1978,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: '\'74 Jailbreak',
    yearReleased: 1984,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Iron Man 2',
    yearReleased: 2010,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Live',
    yearReleased: 1992,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Live at River Plate',
    yearReleased: 2012,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Let There Be Rock: The Movie - Live in Paris',
    yearReleased: 0,
    albumArtist: 'AC/DC',
    albumGenre: '' },
  { idArtist: '119231',
    albumName: 'Live From the Atlantic Studios',
    yearReleased: 1997,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Backtracks',
    yearReleased: 2009,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' },
  { idArtist: '119231',
    albumName: 'Bonfire',
    yearReleased: 1997,
    albumArtist: 'AC/DC',
    albumGenre: 'Hard Rock' } 
  ],
  [ { idArtist: '111393',
    albumName: 'Plastic Beach',
    yearReleased: 2010,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'Gorillaz',
    yearReleased: 2001,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'Demon Days',
    yearReleased: 2005,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'The Fall',
    yearReleased: 2011,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'The Singles Collection 2001-2011',
    yearReleased: 2011,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'DoYaThing',
    yearReleased: 2012,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'D-Sides',
    yearReleased: 2007,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'Greatest Hits',
    yearReleased: 2010,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'G Sides',
    yearReleased: 2001,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'Humanz',
    yearReleased: 2017,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'iTunes Session',
    yearReleased: 2010,
    albumArtist: 'Gorillaz',
    albumGenre: '' },
  { idArtist: '111393',
    albumName: 'The Now Now',
    yearReleased: 2018,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111393',
    albumName: 'Sleeping Powder',
    yearReleased: 2017,
    albumArtist: 'Gorillaz',
    albumGenre: 'Alternative Rock' } 
  ],
  [ { idArtist: '111318',
    artistName: '2Pac',
    albumGenre: 'Hip-Hop',
    website: 'www.2pac.com',
    biography: 'Tupac Amaru Shakur (June 16, 1971 - September 13, 1996), known by his stage names 2Pac, Pac, and Makaveli, was an American rapper and actor. Shakur has sold over 75 million records worldwide as of 2010, making him one of the best-selling music artists in the world. Rolling Stone Magazine named him the 86th Greatest Artist of All Time. The themes of most of Tupac\'s songs are the violence and hardship in inner cities, racism, social problems, and conflicts with other rappers during the East Coast-West Coast hip hop rivalry. Shakur began his career as a roadie, backup dancer, and MC for the alternative hip hop group Digital Underground.' },
  { idArtist: '123600',
    artistName: 'Makaveli',
    albumGenre: 'Hip-Hop',
    website: '',
    biography: 'Makaveli was the alias used by American hip-hop artist, poet, and actor Tupac Shakur while he was with his hip-hop group the Outlawz. The posthumous solo studio album The Don Killuminati: The 7 Day Theory was the only album to be officially released as Makaveli. Future posthumous releases of his with the Outlawz and solo Makaveli recordings were released under Tupac Shakur’s more familiar alias 2Pac. \n\nTupac read and studied the works and life of Niccolo Machiavelli whose ideas were overshadowed by a reputation that was unfairly given to him because of a misunderstanding of his writings and political views. This inspired Tupac to take the name Makaveli as his alias with the Outlawz. With Tupac’s spelling of Makaveli the letters can be rearranged to form the words “Am Alive”.\n\nThe views from a posthumously published pamphlet written by Niccolo Machiavelli called The Prince inspired the term Machiavellian which refers to the view that politics is amoral and that any means can be justifiably used in achieving political power. Tupac named all the original Outlawz after famous Machiavellian leaders who gained power from governments they did not agree with. This made the Outlawz a group of individuals led by Makaveli who were named after individuals who lived their life in a way described by Machiavelli.' } 
  ],
  [ { idArtist: '111318',
    albumName: 'R U Still Down? (Remember Me)',
    yearReleased: 1997,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Still I Rise',
    yearReleased: 1999,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Loyal to the Game',
    yearReleased: 2004,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Strictly 4 My N.I.G.G.A.Z...',
    yearReleased: 1993,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Until the End of Time',
    yearReleased: 2001,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Better Dayz',
    yearReleased: 2002,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Pac\'s Life',
    yearReleased: 2006,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Me Against the World',
    yearReleased: 1995,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: '2Pacalypse Now',
    yearReleased: 1991,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'All Eyez on Me',
    yearReleased: 1996,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Greatest Hits',
    yearReleased: 1998,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'The Here After',
    yearReleased: 1999,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Tupac: Resurrection',
    yearReleased: 2003,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'The Best of 2Pac, Part 1: Thug',
    yearReleased: 2007,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'The Best of 2Pac, Part 2: Life',
    yearReleased: 2007,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'The Lost Tapes',
    yearReleased: 2000,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Thug Revolution',
    yearReleased: 2009,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'One Nation',
    yearReleased: 2010,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Ready 2 Die',
    yearReleased: 2005,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Black Jesuz: The Best Songs',
    yearReleased: 2003,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'The Prophet: The Best of the Works',
    yearReleased: 2003,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Nu-Mixx Klazzics',
    yearReleased: 2003,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Thug Nature',
    yearReleased: 2003,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Rap Phenomenon II',
    yearReleased: 2003,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111318',
    albumName: 'Changes',
    yearReleased: 1998,
    albumArtist: '2Pac',
    albumGenre: 'Hip-Hop' } 
  ],
  [ { idArtist: '111304',
    albumName: 'Encore',
    yearReleased: 2004,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Infinite',
    yearReleased: 1996,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Recovery',
    yearReleased: 2010,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'The Marshall Mathers LP',
    yearReleased: 2000,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'The Slim Shady LP',
    yearReleased: 1999,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Curtain Call: The Hits',
    yearReleased: 2005,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'The Eminem Show',
    yearReleased: 2002,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Relapse',
    yearReleased: 2009,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Relapse: Refill',
    yearReleased: 2009,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Berzerk',
    yearReleased: 2013,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Survival',
    yearReleased: 2013,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'The Monster',
    yearReleased: 2013,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Rap God',
    yearReleased: 2013,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'The Marshall Mathers LP 2',
    yearReleased: 2013,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Straight From the Lab',
    yearReleased: 2003,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Slim Shady EP',
    yearReleased: 1998,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Crack a Bottle',
    yearReleased: 2009,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Stan: A Tribute to Eminem',
    yearReleased: 2003,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'The Singles Boxset',
    yearReleased: 2003,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Raw & Uncut',
    yearReleased: 2006,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'So You Wanna Freestyle?',
    yearReleased: 2008,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Long Time No See',
    yearReleased: 2008,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'A Beautiful Mind',
    yearReleased: 2010,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'Just Don\'t Give a Fuck',
    yearReleased: 1998,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111304',
    albumName: 'My Name Is',
    yearReleased: 1999,
    albumArtist: 'Eminem',
    albumGenre: 'Hip-Hop' } 
  ],
  [ { idArtist: '111766',
    albumName: 'Evanescence',
    yearReleased: 2011,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'The Open Door',
    yearReleased: 2006,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'Origin',
    yearReleased: 2000,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'Fallen',
    yearReleased: 2003,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'Evanescence',
    yearReleased: 1998,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'Mystary EP',
    yearReleased: 2003,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'Anywhere but Home',
    yearReleased: 2004,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'Le Nouveau Gothique',
    yearReleased: 0,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'Greatest Hits',
    yearReleased: 2012,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'Synthesis',
    yearReleased: 2017,
    albumArtist: 'Evanescence',
    albumGenre: 'Rock' },
  { idArtist: '111766',
    albumName: 'Sound Asleep EP',
    yearReleased: 1999,
    albumArtist: 'Evanescence',
    albumGenre: '' } 
  ],
  [ { idArtist: '111710',
    albumName: 'TEN$ION',
    yearReleased: 2012,
    albumArtist: 'Die Antwoord',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111710',
    albumName: '$O$',
    yearReleased: 2009,
    albumArtist: 'Die Antwoord',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111710',
    albumName: '5',
    yearReleased: 2010,
    albumArtist: 'Die Antwoord',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111710',
    albumName: 'Cookie Thumper!',
    yearReleased: 2013,
    albumArtist: 'Die Antwoord',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111710',
    albumName: 'Donker Mag',
    yearReleased: 2014,
    albumArtist: 'Die Antwoord',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111710',
    albumName: 'Mount Ninji and da Nice Time Kid',
    yearReleased: 2016,
    albumArtist: 'Die Antwoord',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111710',
    albumName: 'MADE BY GOD (Chapter I)',
    yearReleased: 2017,
    albumArtist: 'Die Antwoord',
    albumGenre: '' },
  { idArtist: '111710',
    albumName: 'MADE BY GOD (Chapter II)',
    yearReleased: 2017,
    albumArtist: 'Die Antwoord',
    albumGenre: '' },
  { idArtist: '111710',
    albumName: 'MADE BY GOD (Chapter III)',
    yearReleased: 2017,
    albumArtist: 'Die Antwoord',
    albumGenre: '' },
  { idArtist: '111710',
    albumName: 'Suck on This: Pre-Candy Mixtape',
    yearReleased: 2016,
    albumArtist: 'Die Antwoord',
    albumGenre: 'Hip-Hop' },
  { idArtist: '111710',
    albumName: 'Love Drug',
    yearReleased: 2017,
    albumArtist: 'Die Antwoord',
    albumGenre: '' } 
  ],
  [ { idArtist: '111402',
    albumName: 'With Teeth',
    yearReleased: 2005,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Year Zero',
    yearReleased: 2007,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'The Slip',
    yearReleased: 2008,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'The Downward Spiral',
    yearReleased: 1994,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'The Fragile',
    yearReleased: 1999,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Pretty Hate Machine',
    yearReleased: 1989,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Broken',
    yearReleased: 1992,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Fixed',
    yearReleased: 1992,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Further Down the Spiral',
    yearReleased: 1995,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Things Falling Apart',
    yearReleased: 2000,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Live: Beside You in Time',
    yearReleased: 2007,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Closure',
    yearReleased: 1997,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Hesitation Marks',
    yearReleased: 2013,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Deep',
    yearReleased: 2001,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'And All That Could Have Been',
    yearReleased: 2002,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Y34RZ3R0R3M1X3D',
    yearReleased: 2007,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Closer',
    yearReleased: 1994,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'The Day the World Went Away',
    yearReleased: 1999,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Down in It',
    yearReleased: 1989,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Happiness in Slavery',
    yearReleased: 1992,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Head Like a Hole',
    yearReleased: 1990,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'March of the Pigs',
    yearReleased: 1994,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'The Perfect Drug',
    yearReleased: 1996,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Sin',
    yearReleased: 1990,
    albumArtist: 'Nine Inch Nails',
    albumGenre: 'Industrial Metal' },
  { idArtist: '111402',
    albumName: 'Ghosts I–IV',
    yearReleased: 2008,
    albumArtist: 'Nine Inch Nails',
    albumGenre: '' } 
  ],
  [ { idArtist: '111444',
    albumName: 'Diamond Dogs',
    yearReleased: 1974,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Reality',
    yearReleased: 2003,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: '“Heroes”',
    yearReleased: 1977,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'The Man Who Sold the World',
    yearReleased: 1970,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Never Let Me Down',
    yearReleased: 1987,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Space Oddity',
    yearReleased: 1969,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Aladdin Sane',
    yearReleased: 1973,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'David Bowie',
    yearReleased: 1967,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Station to Station',
    yearReleased: 1976,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'The Rise and Fall of Ziggy Stardust and the Spiders From Mars',
    yearReleased: 1972,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Hunky Dory',
    yearReleased: 1971,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Let\'s Dance',
    yearReleased: 1983,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Toy',
    yearReleased: 2011,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Pin Ups',
    yearReleased: 1973,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Young Americans',
    yearReleased: 1975,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Earthling',
    yearReleased: 1997,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Scary Monsters“¦ and Super Creeps',
    yearReleased: 1980,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Lodger',
    yearReleased: 1979,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: '“˜hours“¦\'',
    yearReleased: 1999,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: '1.Outside: The Nathan Adler Diaries: A Hyper Cycle',
    yearReleased: 1995,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Black Tie White Noise',
    yearReleased: 1993,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Low',
    yearReleased: 1977,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'Heathen',
    yearReleased: 2002,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'The Next Day',
    yearReleased: 2013,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' },
  { idArtist: '111444',
    albumName: 'David Live',
    yearReleased: 1974,
    albumArtist: 'David Bowie',
    albumGenre: 'Rock' } 
  ],
  [ { idArtist: '112943',
    albumName: 'Wake Up and Smell the Coffee',
    yearReleased: 2001,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'Roses',
    yearReleased: 2012,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'Bury the Hatchet',
    yearReleased: 1999,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'To the Faithful Departed',
    yearReleased: 1996,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'Everybody Else Is Doing It, so Why Can\'t We?',
    yearReleased: 1993,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'Greatest Hits',
    yearReleased: 2008,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'Stars: The Best of 1992-2002',
    yearReleased: 2002,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'No Need to Argue',
    yearReleased: 1994,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: '20th Century Masters: The Millennium Collection: The Best of The Cranberries',
    yearReleased: 2005,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'Treasure Box: The Complete Sessions, 1991-1999',
    yearReleased: 2002,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'MTV Unplugged',
    yearReleased: 1995,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'Something Else',
    yearReleased: 2017,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112943',
    albumName: 'Uncertain',
    yearReleased: 1991,
    albumArtist: 'The Cranberries',
    albumGenre: '' },
  { idArtist: '112943',
    albumName: 'Bualadh Bos: The Cranberries Live',
    yearReleased: 2009,
    albumArtist: 'The Cranberries',
    albumGenre: '' },
  { idArtist: '112943',
    albumName: 'In the End',
    yearReleased: 2019,
    albumArtist: 'The Cranberries',
    albumGenre: 'Alternative Rock' } 
  ],
  [ { idArtist: '111418',
    albumName: 'Hail to the Thief',
    yearReleased: 2003,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'In Rainbows',
    yearReleased: 2007,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'The King of Limbs',
    yearReleased: 2011,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'OK Computer',
    yearReleased: 1997,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'The Bends',
    yearReleased: 1995,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'Amnesiac',
    yearReleased: 2001,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'Pablo Honey',
    yearReleased: 1993,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'Kid A',
    yearReleased: 2000,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'I Might Be Wrong: Live Recordings',
    yearReleased: 2001,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'The Best Of',
    yearReleased: 2008,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: '2001-06-01: No More Jokes: Rock am Ring, Nürburgring, Germany',
    yearReleased: 0,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'Com Lag: 2plus2isfive',
    yearReleased: 2004,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'Drill',
    yearReleased: 1992,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'Itch',
    yearReleased: 1994,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'Knives Out',
    yearReleased: 2001,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'My Iron Lung',
    yearReleased: 1994,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'No Surprises / Running From Demons',
    yearReleased: 1997,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'No Surprises',
    yearReleased: 1997,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'Oxford\'s Angels',
    yearReleased: 2005,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: '2001-06-04: Pinkpop: Megaland, Landgraaf, Netherlands',
    yearReleased: 2001,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'The Bends Pinkpop',
    yearReleased: 1996,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'There There',
    yearReleased: 2003,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'Oxford Angels: The Rarities',
    yearReleased: 2013,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'A Moon Shaped Pool',
    yearReleased: 2016,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' },
  { idArtist: '111418',
    albumName: 'My Iron Lung',
    yearReleased: 1994,
    albumArtist: 'Radiohead',
    albumGenre: 'Alternative Rock' } 
  ],
  [ { idArtist: '111247',
    albumName: 'The Beatles',
    yearReleased: 1968,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Help!',
    yearReleased: 1965,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Something New',
    yearReleased: 1964,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Revolver',
    yearReleased: 1966,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Abbey Road',
    yearReleased: 1969,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Sgt. Pepper\'s Lonely Hearts Club Band',
    yearReleased: 1967,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Please Please Me',
    yearReleased: 1963,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'With The Beatles',
    yearReleased: 1963,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Rubber Soul',
    yearReleased: 1965,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Yellow Submarine',
    yearReleased: 1969,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'A Hard Day\'s Night',
    yearReleased: 1964,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Magical Mystery Tour',
    yearReleased: 1967,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Let It Be',
    yearReleased: 1970,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Past Masters, Volume One',
    yearReleased: 1988,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Past Masters, Volume Two',
    yearReleased: 1988,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: '1',
    yearReleased: 2000,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Yellow Submarine Songtrack',
    yearReleased: 1999,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Beatles for Sale',
    yearReleased: 1964,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Past Masters',
    yearReleased: 2009,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Anthology 1',
    yearReleased: 1995,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Anthology 2',
    yearReleased: 1996,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Anthology 3',
    yearReleased: 1996,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Love',
    yearReleased: 2006,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Introducing… The Beatles',
    yearReleased: 1964,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' },
  { idArtist: '111247',
    albumName: 'Meet The Beatles!',
    yearReleased: 1964,
    albumArtist: 'The Beatles',
    albumGenre: 'Rock & Roll' } 
  ],
  [ { idArtist: '117722',
    albumName: 'Tribal Derivations',
    yearReleased: 2007,
    albumArtist: 'Beats Antique',
    albumGenre: 'Ambient' },
  { idArtist: '117722',
    albumName: 'Contraption, Volume 2',
    yearReleased: 2012,
    albumArtist: 'Beats Antique',
    albumGenre: 'Ambient' },
  { idArtist: '117722',
    albumName: 'Collide',
    yearReleased: 2008,
    albumArtist: 'Beats Antique',
    albumGenre: 'Ambient' },
  { idArtist: '117722',
    albumName: 'Blind Threshold',
    yearReleased: 2010,
    albumArtist: 'Beats Antique',
    albumGenre: 'Ambient' },
  { idArtist: '117722',
    albumName: 'Elektrafone',
    yearReleased: 2011,
    albumArtist: 'Beats Antique',
    albumGenre: 'Ambient' },
  { idArtist: '117722',
    albumName: 'Shadowbox',
    yearReleased: 2016,
    albumArtist: 'Beats Antique',
    albumGenre: '' },
  { idArtist: '117722',
    albumName: 'Contraption, Volume 1',
    yearReleased: 2009,
    albumArtist: 'Beats Antique',
    albumGenre: '' } 
  ],
  [ { idArtist: '111537',
    albumName: 'To the Sea',
    yearReleased: 2010,
    albumArtist: 'Jack Johnson',
    albumGenre: 'Pop' },
  { idArtist: '111537',
    albumName: 'On and On',
    yearReleased: 2003,
    albumArtist: 'Jack Johnson',
    albumGenre: 'Pop' },
  { idArtist: '111537',
    albumName: 'Brushfire Fairytales',
    yearReleased: 2000,
    albumArtist: 'Jack Johnson',
    albumGenre: 'Pop' },
  { idArtist: '111537',
    albumName: 'Sleep Through the Static',
    yearReleased: 2008,
    albumArtist: 'Jack Johnson',
    albumGenre: 'Pop' },
  { idArtist: '111537',
    albumName: 'In Between Dreams',
    yearReleased: 2005,
    albumArtist: 'Jack Johnson',
    albumGenre: 'Pop' },
  { idArtist: '111537',
    albumName: 'All the Light Above It Too',
    yearReleased: 2017,
    albumArtist: 'Jack Johnson',
    albumGenre: 'Pop' },
  { idArtist: '111537',
    albumName: 'From Here to Now to You',
    yearReleased: 2013,
    albumArtist: 'Jack Johnson',
    albumGenre: 'Pop' },
  { idArtist: '111537',
    albumName: 'Sing-A-Longs and Lullabies for the Film Curious George',
    yearReleased: 2006,
    albumArtist: 'Jack Johnson',
    albumGenre: 'Pop' },
  { idArtist: '111537',
    albumName: 'En Concert',
    yearReleased: 2009,
    albumArtist: 'Jack Johnson',
    albumGenre: 'Pop' } 
  ],
  [ { idArtist: '112952',
    albumName: 'Amanda Palmer Goes Down Under',
    yearReleased: 2011,
    albumArtist: 'Amanda Palmer',
    albumGenre: '' },
  { idArtist: '112952',
    albumName: 'Who Killed Amanda Palmer',
    yearReleased: 2008,
    albumArtist: 'Amanda Palmer',
    albumGenre: '' },
  { idArtist: '112952',
    albumName: 'Theatre Is Evil',
    yearReleased: 2012,
    albumArtist: 'Amanda Palmer',
    albumGenre: '' },
  { idArtist: '112952',
    albumName: 'There Will Be No Intermission',
    yearReleased: 2019,
    albumArtist: 'Amanda Palmer',
    albumGenre: null },
  { idArtist: '112952',
    albumName: 'I Can Spin a Rainbow',
    yearReleased: 2017,
    albumArtist: 'Amanda Palmer',
    albumGenre: '' },
  { idArtist: '112952',
    albumName: 'Piano Is Evil',
    yearReleased: 2016,
    albumArtist: 'Amanda Palmer',
    albumGenre: '' },
  { idArtist: '112952',
    albumName: 'Sketches for the Musical JIB',
    yearReleased: 2016,
    albumArtist: 'Amanda Palmer',
    albumGenre: null } 
  ],
  [ { idArtist: '111641',
    albumName: '26 Mixes for Cash',
    yearReleased: 2003,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Selected Ambient Works, Volume II',
    yearReleased: 1994,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Selected Ambient Works 85““92',
    yearReleased: 1992,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: '...I Care Because You Do',
    yearReleased: 1995,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Richard D. James Album',
    yearReleased: 1996,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Drukqs',
    yearReleased: 2001,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Donkey Rhubarb',
    yearReleased: 1995,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Windowlicker',
    yearReleased: 1999,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Come to Daddy',
    yearReleased: 1997,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'On',
    yearReleased: 1993,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Melodies From Mars',
    yearReleased: 1995,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Rare & Unreleased',
    yearReleased: 2001,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Classics',
    yearReleased: 1994,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Syro',
    yearReleased: 2014,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Cheetah EP',
    yearReleased: 2016,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: '51/13 Aphex Singles Collection',
    yearReleased: 1998,
    albumArtist: 'Aphex Twin',
    albumGenre: 'Electronic' },
  { idArtist: '111641',
    albumName: 'Collapse EP',
    yearReleased: 2018,
    albumArtist: 'Aphex Twin',
    albumGenre: null } 
  ],
  [ { idArtist: '130340',
    albumName: 'In This Episode...',
    yearReleased: 2006,
    albumArtist: 'Lake Street Dive',
    albumGenre: 'Pop' },
  { idArtist: '130340',
    albumName: 'Bad Self Portraits',
    yearReleased: 2014,
    albumArtist: 'Lake Street Dive',
    albumGenre: 'Pop' },
  { idArtist: '130340',
    albumName: 'Lake Street Dive',
    yearReleased: 2010,
    albumArtist: 'Lake Street Dive',
    albumGenre: 'Pop' },
  { idArtist: '130340',
    albumName: 'Promises, Promises',
    yearReleased: 2008,
    albumArtist: 'Lake Street Dive',
    albumGenre: 'Pop' },
  { idArtist: '130340',
    albumName: 'Side Pony',
    yearReleased: 2016,
    albumArtist: 'Lake Street Dive',
    albumGenre: '' },
  { idArtist: '130340',
    albumName: 'Free Yourself Up',
    yearReleased: 2018,
    albumArtist: 'Lake Street Dive',
    albumGenre: 'Pop' } 
  ],
  [ { idArtist: '111492',
    albumName: 'Homework',
    yearReleased: 1997,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'Human After All',
    yearReleased: 2005,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'TRON: Legacy',
    yearReleased: 2010,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'TRON: Legacy R3CONF1GUR3D',
    yearReleased: 2011,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'Discovery',
    yearReleased: 2001,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'Alive 2007',
    yearReleased: 2007,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'Musique, Volume 1: 1993-2005',
    yearReleased: 2006,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'Random Access Memories',
    yearReleased: 2013,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'Daft Club',
    yearReleased: 2003,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'Alive 1997',
    yearReleased: 2001,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'Human After All: Remixes',
    yearReleased: 2006,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: 'Da Funk',
    yearReleased: 1995,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' },
  { idArtist: '111492',
    albumName: '2006-04-29: Coachella Valley Music Festival',
    yearReleased: 2006,
    albumArtist: 'Daft Punk',
    albumGenre: 'House' } 
  ],
  
   
   

   






]