albumCollection = [
  [ { idArtist: '111480',
      albumName: 'Lateralus', 
      yearReleased: 2001, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { 
      idArtist: '111480', 
      albumName: 'Undertow', 
      yearReleased: 1993, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' }, 
    { 
      idArtist: '111480', 
      albumName: '10,000 Days', 
      yearReleased: 2006, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { idArtist: '111480', 
      albumName: 'Ænima', 
      yearReleased: 1996, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { 
      idArtist: '111480', 
      albumName: 'Opiate', 
      yearReleased: 1992, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { 
      idArtist: '111480', 
      albumName: 'Salival', 
      yearReleased: 2000, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { idArtist: '111480', 
      albumName: '72826', 
      yearReleased: 1991, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal' 
    }, 
    { idArtist: '111480', 
      albumName: 'Fear Inoculum', 
      yearReleased: 2019, 
      albumArtist: 'Tool', 
      albumGenre: 'Progressive Metal'
    } 
],
  { idArtist: '112009',
    albumName: Null
  },
  [ { idArtist: '111308',
    albumName: 'Musicology',
    yearReleased: 2004,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Gold Experience',
    yearReleased: 1995,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Camille',
    yearReleased: 1986,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'One Man Jam',
    yearReleased: 2002,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Studio Nights: The Rebels',
    yearReleased: 1979,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Rainbow Children',
    yearReleased: 2001,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Vault... Old Friends 4 Sale',
    yearReleased: 1999,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Dirty Mind',
    yearReleased: 1980,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Undertaker',
    yearReleased: 1993,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Prince',
    yearReleased: 1979,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: '1999',
    yearReleased: 1982,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Chaos and Disorder',
    yearReleased: 1996,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'For You',
    yearReleased: 1978,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Rave Un2 the Joy Fantastic',
    yearReleased: 1999,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Chocolate Invasion',
    yearReleased: 2004,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Controversy',
    yearReleased: 1981,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Lovesexy',
    yearReleased: 1988,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Black Album',
    yearReleased: 1994,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Xpectation',
    yearReleased: 2003,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Crystal Ball',
    yearReleased: 1998,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Come',
    yearReleased: 1994,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Purple Rain',
    yearReleased: 1984,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Sign “☮” the Times',
    yearReleased: 1987,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'Batman',
    yearReleased: 1989,
    albumArtist: 'Prince',
    albumGenre: 'Funk' },
  { idArtist: '111308',
    albumName: 'The Scandalous Sex Suite (feat. Kim Basinger)',
    yearReleased: 1989,
    albumArtist: 'Prince',
    albumGenre: 'Funk' } 
  ],
  [ { idArtist: '111615',
    albumName: 'Fly by Night',
    yearReleased: 1975,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Moving Pictures',
    yearReleased: 1981,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Vapor Trails',
    yearReleased: 2002,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Clockwork Angels',
    yearReleased: 2012,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Hemispheres',
    yearReleased: 1978,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'A Farewell to Kings',
    yearReleased: 1977,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Signals',
    yearReleased: 1982,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Permanent Waves',
    yearReleased: 1980,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Counterparts',
    yearReleased: 1993,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: '2112',
    yearReleased: 1976,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Test for Echo',
    yearReleased: 1996,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Snakes & Arrows',
    yearReleased: 2007,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Caress of Steel',
    yearReleased: 1975,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Hold Your Fire',
    yearReleased: 1987,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Presto',
    yearReleased: 1989,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Roll the Bones',
    yearReleased: 1991,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Power Windows',
    yearReleased: 1985,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Grace Under Pressure',
    yearReleased: 1984,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Rush: Time Machine 2011 - Live in Cleveland',
    yearReleased: 2011,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'All the World\'s a Stage',
    yearReleased: 1976,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Exit... Stage Left',
    yearReleased: 1981,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'A Show of Hands',
    yearReleased: 1989,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Rush',
    yearReleased: 1974,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Different Stages Live',
    yearReleased: 1998,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' },
  { idArtist: '111615',
    albumName: 'Rush in Rio',
    yearReleased: 2003,
    albumArtist: 'Rush',
    albumGenre: 'Progressive Rock' } 
  ],
  [ { idArtist: '112192',
    albumName: 'Morning View',
    yearReleased: 2001,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Make Yourself',
    yearReleased: 1999,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Light Grenades',
    yearReleased: 2006,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'If Not Now, When?',
    yearReleased: 2011,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'S.C.I.E.N.C.E.',
    yearReleased: 1997,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'A Crow Left of the Murder...',
    yearReleased: 2004,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Monuments and Melodies',
    yearReleased: 2009,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'The Essential',
    yearReleased: 2012,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Fungus Amongus',
    yearReleased: 1995,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Live at Lollapalooza 2003',
    yearReleased: 2003,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Enjoy Incubus',
    yearReleased: 1997,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Trust Fall (Side A)',
    yearReleased: 2015,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: '8',
    yearReleased: 2017,
    albumArtist: 'Incubus',
    albumGenre: 'Alternative Rock' },
  { idArtist: '112192',
    albumName: 'Playlist: The Very Best of Incubus',
    yearReleased: 2015,
    albumArtist: 'Incubus',
    albumGenre: '' } 
  ],
  [ { idArtist: '132746',
    albumName: 'Hozier',
    yearReleased: 2014,
    albumArtist: 'Hozier',
    albumGenre: 'Indie Rock' },
  { idArtist: '132746',
    albumName: 'Wasteland, Baby!',
    yearReleased: 2019,
    albumArtist: 'Hozier',
    albumGenre: 'Pop' } 
  ],
  [ { idArtist: '112378',
    artistName: 'Mika',
    albumGenre: 'Pop',
    website: 'www.mikasounds.com',
    biography: 'Mika ( born Michael Holbrook Penniman, Jr.; 18 August 1983) is a British singer-songwriter.\nAfter recording his first extended play, Dodgy Holiday EP, Mika released his first full-length studio album, Life in Cartoon Motion, on Island Records in 2007. Life in Cartoon Motion sold more than 5.6 million copies worldwide and helped Mika win a Brit Award-winning Best British Breakthrough act, and receive a Grammy Award nomination. In 2006, Mika started up his company, Dodgy Holiday Tours Limited. Two years later Mika released his second extended play, Songs for Sorrow, of which limited edition copies are now sold out worldwide. In 2009 Mika released his second studio album, The Boy Who Knew Too Much. Finishing his worldwide tour, Mika started writing and recording material for his third album, The Origin of Love, stating it will be "more simplistic pop, less layered than the last one". The album will be released on 16 September 2012.\nMika was born in Beirut, the third of five children born to a Syrian mother and an American father. When he was a year old his family was forced to leave war-torn Lebanon and moved to Paris. The first piano piece he learned to play was "Les Champs-Élysées", by Joe Dassin. At age seven, he wrote his first song, which he describes as an "awful" piano instrumental called "Angry". The family moved to London when he was nine years old. There, he attended the Lycée Français Charles de Gaulle, where he experienced severe bullying. He also had problems with dyslexia. In response to these experiences Mika was home-schooled by his mother at the age of 12, for six to eight months. He then attended St Philip\'s School in Kensington, where he was the head of the Schola Cantorum (the St. Philip\'s Choir). Later he attended Westminster School and the Royal College of Music, which he left to record his first album at Casablanca Records. He has also slightly altered his given name, Mica, changing the "c" to a "k" because he was frustrated by how often people would mispronounce it.\n\nMika has one younger brother and one younger sister along with two older sisters. His sister Yasmine, who works as an artist under the nom de plume DaWack, painted the cartoon art for his two albums Life in Cartoon Motion and The Boy Who Knew Too Much, and she is currently a fashion designer. Mika speaks French and Spanish fluently; in an interview on 28 September 2009 with The Chris Moyles Show on BBC Radio 1 he commented that he had taken Mandarin Chinese for 9 years but did not speak it very well; he also mentioned that his three sisters did all speak it fluently. He also speaks a little bit of Arabic with a Lebanese dialect, his mother\'s native tongue.\n\nAs a child Mika was trained by Alla Ardakov (Ablaberdyeva), a Russian opera professional, and later attended the Royal College of Music in London. His debut radio appearance was on Dermot O\'Leary\'s BBC Radio 2 show in September 2006. He also appeared on Later... with Jools Holland, and on The Friday Night Project on 19 January 2007. Mika is rumoured to have a vocal range of five octaves, but claims that it is actually closer to three and a half octaves.\n\nMika denied allegations that he is steering clear of sexual taboos in order to appeal to the US market, pointing to the song "Billy Brown", which is about a married man who has an affair with another man. He is quoted as saying, "If I was worried about sexual taboos I certainly wouldn\'t have made the record I made. It has nothing to do with that. It has more to do with self-respect." In an interview in the US gay magazine Out he stated that "there is a way of discussing sexuality without using labels."\n\nIn a September 2009 interview in Gay & Night Mika commented on his sexuality: "I\'ve never ever labelled myself. But having said that; I\'ve never limited my life, I\'ve never limited who I sleep with... Call me whatever you want. Call me bisexual, if you need a term for me..." Later he stated in an interview with This Is London "I consider myself label-less because I could fall in love with anybody - literally - any type, any body. I\'m not picky." In an August 2012 interview with the magazine Instinct, the singer described himself as gay.\n\nIn March 2010, Mika was named in France a Knight of the Order of Arts and Letters for services to music.' } 
  ],
  [ { idArtist: '112378',
    albumName: 'Life in Cartoon Motion',
    yearReleased: 2007,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'The Boy Who Knew Too Much',
    yearReleased: 2009,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'The Origin of Love',
    yearReleased: 2012,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'Songbook, Volume 1',
    yearReleased: 2013,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'Boum Boum Boum',
    yearReleased: 2014,
    albumArtist: 'Mika',
    albumGenre: '' },
  { idArtist: '112378',
    albumName: 'No Place In Heaven',
    yearReleased: 2015,
    albumArtist: 'Mika',
    albumGenre: 'Pop' },
  { idArtist: '112378',
    albumName: 'Popular Song',
    yearReleased: 2012,
    albumArtist: 'MIKA',
    albumGenre: '' },
  { idArtist: '112378',
    albumName: 'My Name Is Michael Holbrook',
    yearReleased: 2019,
    albumArtist: 'MIKA',
    albumGenre: null } 
  ],
  [ { idArtist: '138966',
    albumName: 'Room 93',
    yearReleased: 2014,
    albumArtist: 'Halsey',
    albumGenre: 'Indie Pop' },
  { idArtist: '138966',
    albumName: 'Badlands',
    yearReleased: 2015,
    albumArtist: 'Halsey',
    albumGenre: 'Indie Pop' },
  { idArtist: '138966',
    albumName: 'hopeless fountain kingdom',
    yearReleased: 2017,
    albumArtist: 'Halsey',
    albumGenre: 'Indie Pop' },
  { idArtist: '138966',
    albumName: 'Now or Never',
    yearReleased: 2017,
    albumArtist: 'Halsey',
    albumGenre: '' },
  { idArtist: '138966',
    albumName: 'Strangers',
    yearReleased: 2017,
    albumArtist: 'Halsey',
    albumGenre: '' },
  { idArtist: '138966',
    albumName: 'Without Me',
    yearReleased: 2018,
    albumArtist: 'Halsey',
    albumGenre: 'Indie Pop' },
  { idArtist: '138966',
    albumName: 'Nightmare',
    yearReleased: 2019,
    albumArtist: 'Halsey',
    albumGenre: null },
  { idArtist: '138966',
    albumName: 'Graveyard',
    yearReleased: 2019,
    albumArtist: 'Halsey',
    albumGenre: null },
  { idArtist: '138966',
    albumName: 'clementine',
    yearReleased: 2019,
    albumArtist: 'Halsey',
    albumGenre: null } 
  ],
  [ { idArtist: '113256',
    albumName: 'The Strange Case of...',
    yearReleased: 2012,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'Halestorm',
    yearReleased: 2009,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: '(Don\'t Mess With the) Time Man',
    yearReleased: 1999,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'ReAniMate: The CoVeRs eP',
    yearReleased: 2011,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'ReAniMate 2.0: The CoVeRs eP',
    yearReleased: 2013,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'In the Live Room',
    yearReleased: 2012,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'Into the Wild Life',
    yearReleased: 2015,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'One and Done',
    yearReleased: 2005,
    albumArtist: 'Halestorm',
    albumGenre: 'Metal' },
  { idArtist: '113256',
    albumName: 'Live in Philly 2010',
    yearReleased: 2010,
    albumArtist: 'Halestorm',
    albumGenre: 'Hard Rock' },
  { idArtist: '113256',
    albumName: 'ReAniMate 3.0: The CoVeRs eP',
    yearReleased: 2017,
    albumArtist: 'Halestorm',
    albumGenre: 'Hard Rock' },
  { idArtist: '113256',
    albumName: 'Vicious',
    yearReleased: 2018,
    albumArtist: 'Halestorm',
    albumGenre: 'Hard Rock' } 
  ],
  [ { idArtist: '111939',
    albumName: 'Imaginaerum',
    yearReleased: 2011,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Angels Fall First',
    yearReleased: 1997,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Oceanborn',
    yearReleased: 1998,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Once',
    yearReleased: 2004,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Dark Passion Play',
    yearReleased: 2007,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Wishmaster',
    yearReleased: 2000,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Century Child',
    yearReleased: 2002,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'From Wishes to Eternity: Live',
    yearReleased: 2001,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'End of Innocence',
    yearReleased: 2003,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'End of an Era',
    yearReleased: 2006,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Made in Hong Kong (and in Various Other Places)',
    yearReleased: 2009,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Over the Hills and Far Away',
    yearReleased: 2001,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Wishmastour 2000',
    yearReleased: 2001,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Highest Hopes: The Best of Nightwish',
    yearReleased: 2005,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Imaginaerum (The Score)',
    yearReleased: 2012,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Showtime, Storytime',
    yearReleased: 2013,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Endless Forms Most Beautiful',
    yearReleased: 2015,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Greatest Hits',
    yearReleased: 2008,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Tales From the Elvenpath',
    yearReleased: 2004,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' },
  { idArtist: '111939',
    albumName: 'Decades',
    yearReleased: 2018,
    albumArtist: 'Nightwish',
    albumGenre: 'Symphonic Metal' } ]

]