artistCollection = [
  [ { idArtist: '111480',
      artistName: 'Tool',
      albumGenre: 'Progressive Metal',
      website: 'www.toolband.com',
      biography: 'Tool is an American rock band from Los Angeles, California. Formed in 1990, the group\'s line-up has included drummer Danny Carey, guitarist Adam Jones, and vocalist Maynard James Keenan. Since 1995, Justin Chancellor has been the band\'s bassist, replacing their original bassist Paul D\'Amour. Tool has won three Grammy Awards, performed worldwide tours, and produced albums topping the charts in several countries. The band emerged with a heavy metal sound on their first studio album Undertow in 1993, and later became a dominant act in the alternative metal movement with the release of their second effort, Ã†nima, in 1996. Their efforts to unify musical experimentation, visual arts, and a message of personal evolution continued with Lateralus (2001) and the most recent album 10,000 Days (2006), gaining the band critical acclaim and commercial success around the world.\nDue to Tool\'s incorporation of visual arts and relatively long and complex releases, the band is generally described as a style-transcending act and part of progressive rock and art rock. The relationship between the band and today\'s music industry is ambivalent, at times marked by censorship and the band members\' insistence on privacy.' } 
  ],
  [ { idArtist: '112009',
      artistName: 'System of a Down',
      albumGenre: 'Alternative Metal',
      website: 'www.systemofadown.com',
      biography: 'System of a Down, also known by the acronym SOAD and often shortened to System, is a rock band from Southern California, formed in 1994. It currently consists of Serj Tankian (lead vocals, keyboards, rhythm guitar), Daron Malakian (guitar, vocals), Shavo Odadjian (bass, background vocals) and John Dolmayan (drums).\nThe band achieved commercial success with the release of five studio albums; from which three debuted at number one on the Billboard 200. System of a Down has been nominated for four Grammy Awards, and won the award in 2006 for Best Hard Rock Performance for the song "B.Y.O.B.". The group went on hiatus in August 2006, but reunited in November 2010, embarking on a worldwide tour in 2011.\nSerj Tankian, Daron Malakian, and Shavo Odadjian all attended Rose and Alex Pilibos Armenian School while children, although because of their eight-year age difference they did not meet until 1992 while working on separate projects at the same recording studio. They formed a band named Soil with Tankian on vocals and keyboards, Malakian on vocals and guitar, Dave Hakopyan (who later played in The Apex Theory/Mt. Helium) on bass and Domingo "Dingo" Laranio on drums. The band hired Shavo Odadjian (another Rose and Alex Pilibos alumnus) as manager, although he eventually joined Soil as rhythm guitarist. In 1994, only one live show, and one jam session recording, Hakopyan and Laranio quit the band, feeling that it was not going anywhere.' } 
  ],
  [ { idArtist: '111308',
      artistName: 'Prince',
      albumGenre: 'Funk',
      website: '',
      biography: 'Prince Rogers Nelson (June 7, 1958 – April 21, 2016), known by his mononym Prince, was an American singer, songwriter, multi-instrumentalist and actor, serving as a major figure in popular music for over three decades. Prince was renowned as an innovator and was widely known for his eclectic work, flamboyant stage presence, and wide vocal range. He was widely regarded as the pioneer of Minneapolis sound. His music combined rock, R&B, soul, funk, hip hop, disco, psychedelia, jazz, and pop.\n\nPrince was born in Minneapolis, Minnesota, and developed an interest in music at an early age, writing his first song at age seven. After recording songs with his cousin\'s band 94 East, 19-year-old Prince recorded several unsuccessful demo tapes before releasing his debut album For You in 1978, under the guidance of manager Owen Husney. His 1979 album Prince went platinum due to the success of the singles "Why You Wanna Treat Me So Bad?" and "I Wanna Be Your Lover". His next three records—Dirty Mind (1980), Controversy (1981), and 1999 (1982)—continued his success, showcasing Prince\'s trademark of prominently sexual lyrics and incorporation of elements of funk, dance, and rock music. In 1984, he began referring to his backup band as The Revolution and released Purple Rain, which served as the soundtrack to his film debut of the same name. A prolific songwriter, Prince in the 1980s wrote songs for and produced work by many other acts, often under pseudonyms.\n\nAfter releasing the albums Around the World in a Day (1985) and Parade (1986), The Revolution disbanded and Prince released the critically acclaimed double album Sign "O" the Times (1987) as a solo artist. He released three more solo albums before debuting The New Power Generation band in 1991. He changed his stage name in 1993 to an unpronounceable symbol, also known as the "Love Symbol". He then began releasing new albums at a faster pace to remove himself from contractual obligations to Warner Bros.; he released five records between 1994 and 1996 before signing with Arista Records in 1998. In 2000, he began referring to himself as "Prince" again. He released 15 albums since then, including his latest, HITnRUN Phase One, which was first released exclusively on the Tidal streaming service on September 7, 2015 before being released on CD on September 15, 2015 by NPG Records.\n\nPrince sold over 100 million records worldwide, making him one of the best-selling artists of all time. He won seven Grammy Awards, a Golden Globe, and an Academy Award. He was inducted into the Rock and Roll Hall of Fame in 2004, the first year of his eligibility. Rolling Stone has ranked Prince at number 27 on its list of the 100 Greatest Artists of All Time.\n\nHe died at his Paisley Park recording studio and home in Chanhassen, Minnesota, near Minneapolis, on April 21, 2016, after suffering flu-like symptoms for several weeks.' } 
  ],
  [ { idArtist: '111615',
    artistName: 'Rush',
    albumGenre: 'Progressive Rock',
    website: 'www.rush.com',
    biography: 'Rush is a Canadian rock band formed in August 1968, in the Willowdale neighbourhood of Toronto, Ontario. The band is composed of bassist, keyboardist, and lead vocalist Geddy Lee, guitarist and backing vocalist Alex Lifeson, and drummer, percussionist and lyricist Neil Peart. The band and its membership went through a number of re-configurations between 1968 and 1974, achieving their current form when Peart replaced original drummer John Rutsey in July 1974, two weeks before the group\'s first United States tour. Rutsey\'s departure stemmed primarily from health concerns regarding his diabetes.\n\nSince the release of the band\'s self-titled debut album in March 1974, Rush has become known for its musicianship, complex compositions, and eclectic lyrical motifs drawing heavily on science fiction, fantasy, and philosophy. Rush\'s music style has changed over the years, beginning with blues-inspired heavy metal on their first album, then encompassing hard rock, progressive rock, and a period with heavy use of synthesizers. They have been cited as an influence by various musical artists, including Metallica, Primus, and The Smashing Pumpkins,as well as progressive metal bands such as Dream Theater and Symphony X.\n\nRush has won a number of Juno Awards, and was inducted into the Canadian Music Hall of Fame in 1994. Over their careers, the members of Rush have been acknowledged as some of the most proficient players on their respective instruments, with each band member winning numerous awards in magazine readers\' polls. As a group, Rush possesses 24 gold records and 14 platinum (3 multi-platinum) records. Rush\'s sales statistics place them third behind The Beatles and The Rolling Stones for the most consecutive gold or platinum studio albums by a rock band. Rush also ranks 79th in U.S. album sales, with 25 million units. Although total worldwide album sales are not calculated by any single entity, as of 2004 several industry sources estimated Rush\'s total worldwide album sales at over 40 million units.\n\nThe band finished the second leg of the Time Machine Tour in July 2011 and released their latest studio album, Clockwork Angels in June 2012 with a supporting tour in the fall.' } 
  ],
  [ { idArtist: '112192',
    artistName: 'Incubus',
    albumGenre: 'Alternative Rock',
    website: 'www.enjoyincubus.com',
    biography: 'Incubus is an American rock band from Calabasas, California. The band was formed in 1991 by vocalist Brandon Boyd, lead guitarist Mike Einziger, and drummer Jose Pasillas while enrolled in high school and later expanded to include bassist Alex "Dirk Lance" Katunich, and Gavin "DJ Lyfe" Koppell; both of whom were eventually replaced by bassist Ben Kenney and DJ Kilmore respectively.\nIncubus has received both critical acclaim and commercial success, reaching multi-platinum sales, as well as releasing several highly successful singles. The band earned mainstream recognition with the release of their 1999 album Make Yourself. In 2001, Incubus became even more successful with the single "Drive" and their follow-up album Morning View. Their sixth studio album, Light Grenades, debuted at No. 1 in 2006 and has received Gold certification in the U.S. Incubus released their first greatest hits album Monuments and Melodies in June 2009, accompanied by a tour of the United States, Japan and Canada. The band recently completed a seventh album, If Not Now, When?, which was released on July 12, 2011.' } 
  ],
  
]